
services:
  main:
    container_name: cashbook4
    depends_on: 
      - "db"
    image: dingdangdog/cashbook:4.0.8
    restart: always
    # network_mode: "host"
    volumes:
      - ./data:/app/data # 数据挂载到本地，不建议修改
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@cashbook_db:5432/cashbook?schema=public" # 数据库链接，【请自行修改！与你的数据库一致】
      NUXT_DATA_PATH: "/app/data" # 数据存储未知，现在只有小票图片了，不建议修改
      NUXT_AUTH_SECRET: "auth_secret" # 前台登录加密使用的密钥 【自行修改！】
      NUXT_ADMIN_USERNAME: "admin" # 后台登录用户名
      # 【自行修改】后台登录密码，密码是加密后的，生成密码可前往 https://cashbook.oldmoon.top/admin/GetPassword 或独立部署后访问 `你的url/admin/GetPassword`
      NUXT_ADMIN_PASSWORD: "fb35e9343a1c095ce1c1d1eb6973dc570953159441c3ee315ecfefb6ed05f4cc"
    ports:
      - 9090:9090 # 账本开放端口 【自行修改！】
  db:
    container_name: cashbook_db
    image: postgres
    restart: always
    #network_mode: "host"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./db:/var/lib/postgresql/data # 数据库容器数据挂载到本地，不建议修改
    environment:
      #POSTGRES_USER: postgres # 数据库用户名，不填默认为postgres
      POSTGRES_PASSWORD: postgres # 数据库密码 【自行修改！】
      POSTGRES_DB: cashbook
    #ports:
    #  - 5432:5432 # 数据库端口，想要远程连接请放开注释，并建议自行修改端口