
services:
  main:
    container_name: cashbook4
    image: dingdangdog/cashbook:4.1.0-sqlite
    restart: always
    volumes:
      - ./data:/app/data # SQLite database and data files
    environment:
      DATABASE_URL: "file:/app/data/db/cashbook.db" # SQLite database path
      NUXT_DATA_PATH: "/app/data"
      NUXT_AUTH_SECRET: "auth_secret" # 前台登录加密使用的密钥 【自行修改！】
      NUXT_ADMIN_USERNAME: "admin" # 后台登录用户名
      # 【自行修改】后台登录密码，密码是加密后的，生成密码可前往 https://cashbook.oldmoon.top/admin/GetPassword 或独立部署后访问 `你的url/admin/GetPassword`
      NUXT_ADMIN_PASSWORD: "fb35e9343a1c095ce1c1d1eb6973dc570953159441c3ee315ecfefb6ed05f4cc"
    ports:
      - 9090:9090 # 账本开放端口 【自行修改！】
